### ISSUE TITLE
When inside modal popup, popovers are not shown inside popup

### ISSUE THREAD

**Issue by mrdnote** [mingliangfeng/jquery.validate.bootstrap.popover#9]
I have a page where some required fields are in the page itself and some are in a modal popup. When the page is validated the errors are shown under the popup. Is there a solution to this problem?
![image](https://cloud.githubusercontent.com/assets/5628584/13205480/7f3fd9cc-d8e9-11e5-93ee-eb03c2bf0a5e.png)

**Comment by mingliangfeng** [comment]
You can try to adjust the z-index value of the error popup or you modal popup.

**Comment by mrdnote** [comment]
Hi thanks for your suggestion. The problem is the z-index is applied to ALL popovers. So then popovers for the underlying screen are shown on top of the popup and not on their own "layer".

**Comment by mrdnote** [comment]
Hi @mingliangfeng , I requested a pull which solves this problem: pull #10 . Hope you find it useful!

**Comment by mingliangfeng** [comment]
resolved by @mrdnote in https://github.com/mingliangfeng/jquery.validate.bootstrap.popover/pull/10
